services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - HTTP_HOST=0.0.0.0
      - HTTP_PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=authentication_user
      - DB_PASSWORD=authentication_password
      - DB_NAME=authentication_db
      - DB_SSLMODE=disable
    networks:
      - authentication-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=authentication_user
      - POSTGRES_PASSWORD=authentication_password
      - POSTGRES_DB=authentication_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U authentication_user -d authentication_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - authentication-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  authentication-network:
    driver: bridge

volumes:
  postgres_data:
